sudo: false
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
      - "irc.mozilla.org#fireplace"
    on_success: change
    on_failure: change
  email: false
language: node_js
python:
  - "2.7"
node_js:
  - "0.10"
env:
  - RUN_TEST=uitest-phantom UPLOAD_CAPTURES=1 SHOW_TEST_CONSOLE=1
  - RUN_TEST=uitest-slimer UPLOAD_CAPTURES=1 SHOW_TEST_CONSOLE=1
  - RUN_TEST=jshint
  - RUN_TEST=unittest
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - 'export SLIMERJSLAUNCHER=$(which firefox)'
# Create an installation.
  - "make install"
# Setup xvfb for karma and slimerjs.
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
# Start the server
  - 'make serve &'
  - 'sleep 10'
script:
  - 'make $RUN_TEST'
cache:
  directories:
    - /tmp/pip-cache
    - /tmp/python-env
    - node_modules
    - bower_components
